import streamlit as st
import io
from styles.theme import page_header
from utils.scoring import generate_risks, score_label


def _generate_pdf(r: dict) -> bytes:
    """Generate PDF report bytes using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        Table, TableStyle, HRFlowable)

        buf    = io.BytesIO()
        doc    = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                                   leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        label, color_str = score_label(r["final_score"])

        BLUE  = colors.HexColor("#0A2342")
        LIGHT = colors.HexColor("#1A73E8")

        title_style = ParagraphStyle("Title", parent=styles["Title"],
                                     textColor=BLUE, fontSize=22, spaceAfter=4)
        h2_style    = ParagraphStyle("H2", parent=styles["Heading2"],
                                     textColor=LIGHT, fontSize=13, spaceAfter=6)
        normal      = ParagraphStyle("N", parent=styles["Normal"], fontSize=10,
                                     leading=15, textColor=colors.HexColor("#374151"))

        story = [
            Paragraph("AI Resume Intelligence Platform", title_style),
            Paragraph("Candidate Evaluation Report — Confidential", normal),
            HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=14),

            Paragraph("Executive Summary", h2_style),
            Paragraph(
                f"Candidate resume evaluated for the role of <b>{r['selected_role']}</b>. "
                f"The AI model assigned a score of <b>{r['final_score']}/9.0</b> ({label}), "
                f"with a job alignment of <b>{r['job_match_pct']}%</b>.",
                normal
            ),
            Spacer(1, 0.4*cm),

            Paragraph("Score Breakdown", h2_style),
        ]

        table_data = [
            ["Dimension", "Score (/10)", "Assessment"],
            ["Skills Strength",    f"{r['skills_score']:.1f}", "Strong" if r['skills_score'] >= 7 else "Needs Improvement"],
            ["Experience Depth",   f"{r['exp_score']:.1f}",   "Adequate" if r['exp_score'] >= 5 else "Below Threshold"],
            ["Achievement Impact", f"{r['ach_score']:.1f}",   "Impactful" if r['ach_score'] >= 6 else "Add Metrics"],
            ["Job Similarity",     f"{r['job_sim']:.1f}",     "Aligned" if r['job_sim'] >= 6 else "Low Alignment"],
            ["FINAL SCORE",        f"{r['final_score']:.1f}", label],
        ]
        tbl = Table(table_data, colWidths=[6*cm, 3*cm, 6*cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, 0), BLUE),
            ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#F8FAFC"), colors.white]),
            ("GRID",         (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 7),
            ("TOPPADDING",   (0, 0), (-1, -1), 7),
            ("FONTNAME",     (0, -1), (-1, -1), "Helvetica-Bold"),
        ]))
        story.extend([tbl, Spacer(1, 0.4*cm)])

        # Strengths
        story.append(Paragraph("Detected Strengths", h2_style))
        if r["matching_skills"]:
            story.append(Paragraph(", ".join(r["matching_skills"]), normal))
        story.append(Spacer(1, 0.3*cm))

        # Risks
        story.append(Paragraph("Risk Factors & Recommendations", h2_style))
        risks = generate_risks(r)
        for risk in risks:
            story.append(Paragraph(f"<b>{risk['severity']} Risk — {risk['title']}</b>", normal))
            story.append(Paragraph(f"Issue: {risk['explanation']}", normal))
            story.append(Paragraph(f"Fix: {risk['fix']}", normal))
            story.append(Spacer(1, 0.25*cm))

        # Footer
        story.extend([
            HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=8),
            Paragraph("Generated by AI Resume Intelligence Platform — Confidential | For internal HR use only.",
                       ParagraphStyle("footer", parent=normal, fontSize=8, textColor=colors.HexColor("#94A3B8"))),
        ])

        doc.build(story)
        return buf.getvalue()
    except ImportError:
        return b""  # graceful fallback


def show():
    page_header("Generate Report", "Download a professional AI-generated evaluation PDF")

    if "result" not in st.session_state:
        st.info("⬅️  Please upload a resume on the **Resume Upload** page first.")
        return

    r = st.session_state["result"]
    label, color = score_label(r["final_score"])

    col_preview, col_action = st.columns([1.8, 1])

    with col_preview:
        st.markdown('<div class="section-header">Report Preview</div>', unsafe_allow_html=True)
        risks = generate_risks(r)
        strengths_html = "".join(f'<span class="skill-tag-match">{s}</span>' for s in r["matching_skills"])
        weaknesses_html = "".join(
            f'<div style="font-size:12px;color:#991B1B;margin-bottom:4px;">⚠ {iss["title"]}</div>'
            for iss in risks if iss["severity"] == "High"
        )

        import re
        html_str = re.sub(r"^\s+", "", f"""
<div style="background:white;border-radius:14px;padding:32px;box-shadow:0 4px 20px rgba(10,35,66,0.10);border-top:5px solid #1A73E8;">
<div style="text-align:center;margin-bottom:24px;">
<div style="font-size:11px;font-weight:700;color:#94A3B8;text-transform:uppercase;letter-spacing:1px;">AI Resume Intelligence Platform</div>
<div style="font-size:22px;font-weight:800;color:#0A2342;margin:8px 0;">Candidate Evaluation Report</div>
<div style="font-size:12px;color:#94A3B8;">Confidential — Internal HR Use</div>
</div>
<hr style="border:none;border-top:1px solid #E2E8F0;margin:18px 0;">
<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;margin-bottom:20px;text-align:center;">
<div style="padding:14px;background:#F8FAFC;border-radius:10px;">
<div style="font-size:10px;color:#64748B;font-weight:700;text-transform:uppercase;">Final Score</div>
<div style="font-size:28px;font-weight:900;color:{color};">{r['final_score']}/9</div>
<div style="font-size:11px;color:{color};font-weight:600;">{label}</div>
</div>
<div style="padding:14px;background:#F8FAFC;border-radius:10px;">
<div style="font-size:10px;color:#64748B;font-weight:700;text-transform:uppercase;">Job Match</div>
<div style="font-size:28px;font-weight:900;color:#1A73E8;">{r['job_match_pct']:.0f}%</div>
<div style="font-size:11px;color:#64748B;">{r['selected_role']}</div>
</div>
<div style="padding:14px;background:#F8FAFC;border-radius:10px;">
<div style="font-size:10px;color:#64748B;font-weight:700;text-transform:uppercase;">Experience</div>
<div style="font-size:28px;font-weight:900;color:#8B5CF6;">{r['exp_years']:.0f}y</div>
<div style="font-size:11px;color:#64748B;">Professional</div>
</div>
</div>
<div style="margin-bottom:16px;">
<div style="font-size:12px;font-weight:700;color:#065F46;margin-bottom:8px;">✅ Strengths</div>
{strengths_html if strengths_html else '<span style="color:#94A3B8;font-size:12px;">—</span>'}
</div>
<div style="margin-bottom:16px;">
<div style="font-size:12px;font-weight:700;color:#991B1B;margin-bottom:6px;">⚠ Key Risks</div>
{weaknesses_html if weaknesses_html else '<div style="font-size:12px;color:#10B981;">No high-severity risks detected.</div>'}
</div>
</div>
        """, flags=re.MULTILINE)
        st.markdown(html_str, unsafe_allow_html=True)

    with col_action:
        st.markdown('<div class="section-header">Download Options</div>', unsafe_allow_html=True)
        st.markdown("""
        <div style="background:white;border-radius:12px;padding:24px;
                    box-shadow:0 2px 8px rgba(10,35,66,0.07);">
            <div style="font-size:13px;color:#374151;margin-bottom:16px;">
                Click below to generate and download the full PDF evaluation report.
            </div>
        """, unsafe_allow_html=True)

        pdf_bytes = _generate_pdf(r)
        if pdf_bytes:
            st.download_button(
                label="📄  Download PDF Report",
                data=pdf_bytes,
                file_name="AI_Resume_Intelligence_Report.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        else:
            st.warning("reportlab not installed — install it to enable PDF downloads.")

        st.markdown("""
            <div style="margin-top:16px;font-size:11px;color:#94A3B8;line-height:1.7;">
                📋 Report includes:<br>
                • Executive summary<br>
                • Score breakdown table<br>
                • Matched skill list<br>
                • Risk factors & fixes<br>
                • Job alignment summary
            </div>
        </div>
        """, unsafe_allow_html=True)
